name: cinescope
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

 
 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/Thebatman.jpeg
    - assets/images/F1.jpg
    - assets/images/inception-1.jpg
    - assets/images/Warrior.jpeg
    - assets/images/one-love.jpg
    - assets/images/300.jpeg
    - assets/images/interstellar.jpg
    - assets/images/shawshank.jpeg
    - assets/images/pulp_fiction.jpg
    - assets/images/dark_knight.jpg
    - assets/images/battinson.jpg

